CREATE TABLE benchmarks (
    start_x INTEGER NOT NULL,
    start_y INTEGER NOT NULL,
    start_z INTEGER NOT NULL,
    end_x INTEGER NOT NULL,
    end_y INTEGER NOT NULL,
    end_z INTEGER NOT NULL,
    "Dijkstra / PriorityQueue: cost" INTEGER NOT NULL,
    "Dijkstra / PriorityQueue: computeTimeMs" INTEGER NOT NULL,
    "Dijkstra / PriorityQueue: expandedVertices" INTEGER NOT NULL,
    "Dijkstra / BucketQueue: cost" INTEGER NOT NULL,
    "Dijkstra / BucketQueue: computeTimeMs" INTEGER NOT NULL,
    "Dijkstra / BucketQueue: expandedVertices" INTEGER NOT NULL,
    "Dijkstra / ArrayQueue: cost" INTEGER NOT NULL,
    "Dijkstra / ArrayQueue: computeTimeMs" INTEGER NOT NULL,
    "Dijkstra / ArrayQueue: expandedVertices" INTEGER NOT NULL,
    "Dijkstra-Backwards / PriorityQueue: cost" INTEGER NOT NULL,
    "Dijkstra-Backwards / PriorityQueue: computeTimeMs" INTEGER NOT NULL,
    "Dijkstra-Backwards / PriorityQueue: expandedVertices" INTEGER NOT NULL,
    "Dijkstra-Backwards / BucketQueue: cost" INTEGER NOT NULL,
    "Dijkstra-Backwards / BucketQueue: computeTimeMs" INTEGER NOT NULL,
    "Dijkstra-Backwards / BucketQueue: expandedVertices" INTEGER NOT NULL,
    "Dijkstra-Backwards / ArrayQueue: cost" INTEGER NOT NULL,
    "Dijkstra-Backwards / ArrayQueue: computeTimeMs" INTEGER NOT NULL,
    "Dijkstra-Backwards / ArrayQueue: expandedVertices" INTEGER NOT NULL,
    "BFS / UnweightedQueue: cost" INTEGER NOT NULL,
    "BFS / UnweightedQueue: computeTimeMs" INTEGER NOT NULL,
    "BFS / UnweightedQueue: expandedVertices" INTEGER NOT NULL,
    "BFS-Backwards / UnweightedQueue: cost" INTEGER NOT NULL,
    "BFS-Backwards / UnweightedQueue: computeTimeMs" INTEGER NOT NULL,
    "BFS-Backwards / UnweightedQueue: expandedVertices" INTEGER NOT NULL,
    "BFS-MeetInMiddle / UnweightedQueue: cost" INTEGER NOT NULL,
    "BFS-MeetInMiddle / UnweightedQueue: computeTimeMs" INTEGER NOT NULL,
    "BFS-MeetInMiddle / UnweightedQueue: expandedVertices" INTEGER NOT NULL,
    "BFS-MeetAtTeleport / UnweightedQueue: cost" INTEGER NOT NULL,
    "BFS-MeetAtTeleport / UnweightedQueue: computeTimeMs" INTEGER NOT NULL,
    "BFS-MeetAtTeleport / UnweightedQueue: expandedVertices" INTEGER NOT NULL
);