SELECT
    AVG("Dijkstra / ArrayQueue: cost") AS "cost",
    AVG("Dijkstra / PriorityQueue: computeTimeMs") AS "D/P t",
    AVG("Dijkstra / PriorityQueue: expandedVertices") AS "D/P v",
    AVG("Dijkstra / BucketQueue: computeTimeMs") AS "D/B t",
    AVG("Dijkstra / BucketQueue: expandedVertices") AS "D/B v",
    AVG("Dijkstra / ArrayQueue: computeTimeMs") AS "D/A t",
    AVG("Dijkstra / ArrayQueue: expandedVertices") AS "D/A v",
    AVG("Dijkstra-Backwards / PriorityQueue: computeTimeMs") AS "DB/P t",
    AVG("Dijkstra-Backwards / PriorityQueue: expandedVertices") AS "DB/P v",
    AVG("Dijkstra-Backwards / BucketQueue: computeTimeMs") AS "DB/B t",
    AVG("Dijkstra-Backwards / BucketQueue: expandedVertices") AS "DB/B v",
    AVG("Dijkstra-Backwards / ArrayQueue: computeTimeMs") AS "DB/A t",
    AVG("Dijkstra-Backwards / ArrayQueue: expandedVertices") AS "DB/A v",
    AVG("BFS / UnweightedQueue: computeTimeMs") AS "B t",
    AVG("BFS / UnweightedQueue: expandedVertices") AS "B v",
    AVG("BFS-Backwards / UnweightedQueue: computeTimeMs") AS "BB t",
    AVG("BFS-Backwards / UnweightedQueue: expandedVertices") AS "BB v",
    AVG("BFS-MeetInMiddle / UnweightedQueue: computeTimeMs") AS "BMITM t",
    AVG("BFS-MeetInMiddle / UnweightedQueue: expandedVertices") AS "BMITM v",
    AVG("BFS-MeetAtTeleport / UnweightedQueue: computeTimeMs") AS "BMATP t",
    AVG("BFS-MeetAtTeleport / UnweightedQueue: expandedVertices") AS "BMATP v"
FROM benchmarks;